### ISSUE TITLE
Sent non-empty 'Sec-WebSocket-Protocol'

### ISSUE THREAD

**Issue by Falseclock** [appuri/robust-websocket#12]
Getting error

WebSocket connection to 'ws://beta:12346/RateInformer' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

on line

realWs = new WebSocket(url, protocols)

**Comment by swilsonnc** [comment]
Try realWs = new RobustWebSocket(url, protocols) maybe??

**Comment by marutha** [comment]
+1 I am getting the same problem, Any clues or guides to solve?

**Comment by swilsonnc** [comment]
I think your problem is your trying to connect to a folder at the server.  Websocket is a protocol so it doesn't do folders.  The pc/server/ip address running the websocket server is listening on the port, that is it.  Remove the folder, /RateInformer from the line and try again.  Also make sure you use RobustWebSocket in your line rather than WebSocket.  The former has to be there to use RobustWebSocket or your just not using it at all.

**Comment by nathanboktae** [comment]
This is an issue with your server, not with this library. Easy way to confirm​ is just use the native websocket.

**Comment by Falseclock** [comment]
Native library works perfectly

**Comment by nathanboktae** [comment]
How are you calling the native library?

**Comment by Falseclock** [comment]
@nathanboktae 

new WebSocket('ws://beta:12346/RateInformer');

**Comment by rdbhost** [comment]
passing undefined as the second parameter seems to work better than null.

        var conn =  new RobustWebSocket('wss://'+HOST+'/ws/', undefined, {
            shouldReconnect: function(event, ws) {
                return Math.pow(1.5, ws.attempts) * 500;
            }
        });

using null got me the 'sent non-empty 'Sec-WebSocket-Protocol' error.
